"""
Unified email service for sending due list reports
"""
import os
from datetime import datetime
import pytz

# Import from unified portal modules
from utils.config import EMAIL_RECIPIENTS
from utils.state_manager import processed_emails_state, save_processed_emails
from utils.scheduler import get_est_time


def send_due_list_email(excel_file_path=None):
    """Send email with job_tracker_report.xlsx Excel attachment to MULTIPLE recipients"""
    print(f"\n📧 SENDING DUE LIST EMAIL TO {len(EMAIL_RECIPIENTS)} RECIPIENTS...")
    print("=" * 50)
    print(f"👥 Recipients: {', '.join(EMAIL_RECIPIENTS)}")
    
    # FORCE job_tracker_report.xlsx - ignore any other file paths
    excel_file_path = "job_tracker_report.xlsx"
    print(f"📎 ATTACHMENT: {excel_file_path} (FORCED)")
    
    try:
        # Try to use VMS email sender first
        from services.vms.email_sender import send_excel_report_email
        
        if not os.path.exists(excel_file_path):
            print(f"❌ Excel file not found: {excel_file_path}")
            return False
            
        file_size = os.path.getsize(excel_file_path)
        if file_size == 0:
            print(f"❌ Excel file is empty: {excel_file_path}")
            return False
            
        print(f"✅ Excel file verified: {excel_file_path} ({file_size} bytes)")
        
        print(f"📤 Attempting to send email with attachment: {excel_file_path}")
        
        # Send to all recipients using VMS1 system
        all_success = True
        for recipient in EMAIL_RECIPIENTS:
            try:
                # Try calling without recipient_email parameter first
                success = send_excel_report_email(
                    excel_file_path=excel_file_path,
                    subject_prefix="Daily Job Tracker Report"
                )
                
                if success:
                    print(f"✅ Due List email sent successfully to {recipient}!")
                else:
                    print(f"❌ Failed to send Due List email to {recipient}")
                    all_success = False
                    
            except TypeError as e:
                # If still fails, try fallback immediately
                print(f"🔄 VMS1 email failed, using fallback for {recipient}")
                success = send_due_list_email_fallback_single(excel_file_path, recipient)
                if not success:
                    all_success = False
            except Exception as e:
                print(f"❌ Error sending to {recipient}: {e}")
                all_success = False
        
        return all_success
            
    except ImportError as e:
        print(f"❌ Could not import VMS1 email system: {e}")
        print("🔄 Falling back to HHSC email system...")
        return send_due_list_email_fallback(excel_file_path)
    except Exception as e:
        print(f"❌ Error sending due list email: {e}")
        import traceback
        traceback.print_exc()
        return False

def send_due_list_email_fallback(excel_file_path):
    """Fallback email sending using HHSC system if VMS fails - UPDATED FOR MULTIPLE RECIPIENTS"""
    try:
        from services.dir.email_sender import HHSCOutlookEmailSender
        
        email_sender = HHSCOutlookEmailSender()
        
        subject = f"Daily Job Tracker Report - {datetime.now().strftime('%Y-%m-%d')}"
        
        body = f"""
        <html>
        <body>
            <h2>Daily Job Tracker Report</h2>
            <p>Please find attached the daily job tracker report generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}.</p>
            
            <h3>Report Contents:</h3>
            <ul>
                <li><strong>Active Jobs</strong> - Jobs that are currently active and not past due</li>
                <li><strong>Past Due Jobs</strong> - Jobs that are past their due date</li>
            </ul>
            
            <p>This report contains all tracked job applications with submission counts.</p>
            
            <br>
            <p><em>This email was automatically generated by the Unified Portal System.</em></p>
        </body>
        </html>
        """
        
        # Send to all recipients
        all_success = True
        for recipient in EMAIL_RECIPIENTS:
            # Note: HHSC email sender might not have send_email method
            # You may need to adapt this based on actual HHSC email sender capabilities
            try:
                # Try using HHSC email sender's method
                success = email_sender.send_solicitation_email(
                    req_number="DAILY_REPORT",
                    title="Daily Job Tracker Report",
                    body_content=body,
                    document_paths=[excel_file_path]
                )
                
                if success:
                    print(f"✅ Due List email sent successfully to {recipient} using HHSC fallback system!")
                else:
                    print(f"❌ Failed to send Due List email to {recipient} with fallback system")
                    all_success = False
            except Exception as e:
                print(f"❌ HHSC fallback failed for {recipient}: {e}")
                all_success = False
        
        return all_success
            
    except Exception as e:
        print(f"❌ Fallback email system also failed: {e}")
        return False

def send_due_list_email_fallback_single(excel_file_path, recipient_email):
    """Fallback email sending for single recipient"""
    try:
        from services.dir.email_sender import HHSCOutlookEmailSender
        
        email_sender = HHSCOutlookEmailSender()
        
        subject = f"Daily Job Tracker Report - {datetime.now().strftime('%Y-%m-%d')}"
        
        body = f"""
        <html>
        <body>
            <h2>Daily Job Tracker Report</h2>
            <p>Please find attached the daily job tracker report generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}.</p>
            
            <h3>Report Contents:</h3>
            <ul>
                <li><strong>Active Jobs</strong> - Jobs that are currently active and not past due</li>
                <li><strong>Past Due Jobs</strong> - Jobs that are past their due date</li>
            </ul>
            
            <p>This report contains all tracked job applications with submission counts.</p>
            
            <br>
            <p><em>This email was automatically generated by the Unified Portal System.</em></p>
        </body>
        </html>
        """
        
        # Try using HHSC email sender's method
        success = email_sender.send_solicitation_email(
            req_number="DAILY_REPORT",
            title="Daily Job Tracker Report",
            body_content=body,
            document_paths=[excel_file_path]
        )
        
        if success:
            print(f"✅ Due List email sent successfully to {recipient_email} using HHSC fallback system!")
        else:
            print(f"❌ Failed to send Due List email to {recipient_email} with fallback system")
        
        return success
            
    except Exception as e:
        print(f"❌ Fallback email system also failed for {recipient_email}: {e}")
        return False